config/routes.rb
Rails.application.routes.draw do
  
  resources :words, only: [:index, :create, :edit,:destroy]
  get 'words/quiz', to: 'words#quiz',as: 'quiz'
  get 'words/quiz_answer/:id', to: 'words#quiz_answer',as: 'answer'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root to: 'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'sign_up', to: 'users#new'
  resources :users, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
   before_save { self.email.downcase! }
   validates :name, presence: true, length: { maximum: 50 }
   validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :words
 
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user
   validates :word, presence: true, length: { maximum: 50 }
   validates :meaning, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  def check_user_logged_in
    unless logged_in?
    redirect_to root_url
    end 
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   before_action :check_user_logged_in , only: [:destroy]
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログイン完了'
      redirect_to words_url
    else
      flash.now[:danger]='ログイン失敗'
      render :new
    end 
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  private
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end 
  end 

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if  @user.save
      flash[:success] = 'ユーザー登録完了！ログインしてください'
      redirect_to login_url
    else
      flash.now[:danger]='ユーザー登録に失敗しました'
      render :new
    end 
  end
 
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 
  
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :check_user_logged_in, only: [:index, :quiz]
  
  
  def index
    @words = current_user.words.page(params[:page]).per(20)
    @word = current_user.words.build
  end

  def create
    @word = current_user.words.build(word_params)
    if @word.save
      redirect_to words_url
    else
      @words = current_user.words
      render :index
    end 
  end

  def edit
  end

  def destroy
     @word = Word.find(params[:id])#each.doのなかで削除ボタンつけれるようになった
     @word.destroy
     redirect_to words_url
  end
  def quiz
  @quiz = current_user.words.sample
  end 
  def quiz_answer
    @answer = current_user.words.find(params[:id])
  end 
  
  private
  def word_params
  params.require(:word).permit(:word, :meaning)
  end 
  def check_user_logged_in
    unless logged_in?
    redirect_to root_url
    end 
  end 
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end 
  
  def logged_in?
    !!current_user
  end 
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>

<div class='alert alert-<%= message_type %>'><%= message %></div>

<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">YOUR TANGO</a>
		</div>
		
		<div class="collapse navbar-collapse" id="navbarEexample1">
			<ul class="nav navbar-nav">
				<li><a href="/words">単語リスト</a></li>
				<li><a href="/words/quiz">単語クイズ</a></li>
				<li><a href="/sessions/destroy">ログアウト</a></li>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Yourtango</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   <!--bootstrapのjqueryの読み込みコードはjavascriptより上に書かないと正常に機能しないことので注意！！-->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
<div class="container-fluid ">
<div class='row'>
<div class='col-md-8 col-md-offset-2 '>
  <div class="page-header">
	<h2><%= current_user.name %>の単語登録数</h2>
</div>
<div class='words_count'>
  <p><%= current_user.words.count %></p>
</div>
</div>
</div>
</div>
<% else %>

<div class="jumbotron jubotoron_add">
<div class="container-fluid ">
  <h1>YOUR TANGO</h1>
  <p>YOUR TANGOとは、、、あなただけの単語リストとあなただけの単語クイズをお手軽に作成して、あなたの単語学習を手助けするアプリです</p>
    <%= link_to '新規登録',sign_up_path,class:'btn btn-default btn-lg btn-move' %>
    <%= link_to 'ログイン',login_path,class:'btn btn-default btn-lg btn-move' %>
</div>
</div>

<% end %>

app/views/users/new.html.erb
<div class='container-fluid'>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> 下記が原因で登録に失敗しました:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
         </ul>
    </div>
  <% end %>
<div class='row'>
<div class='col-md-offset-2 col-md-8'>
<%= form_for(@user) do |f| %>
<div class='form-group'>
<%= f.label :name, 'Name' %>
<%= f.text_field :name, class:'form-control' %>
</div>
<div class='form-group'>
<%= f.label :email, 'Email' %>
<%= f.email_field :email, class:'form-control' %>
</div>
<div class='form-group'>
<%= f.label :password, 'Password' %>
<%= f.password_field :password, class:'form-control' %>
</div>
<div class='form-group'>
<%= f.label :password_confirmation, 'Password Confirmation' %>
<%= f.password_field :password_confirmation, class:'form-control' %>
</div>
<%= f.submit '新規登録', class:'btn btn-primary' %>

<% end %>

<p>既存のユーザーの方は</p>
<%= link_to 'ログインページへ', login_path, class:'btn btn-warning' %>

</div>
</div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<%= @user.name %>

<%= link_to 'トップページへ',root_path %>

app/views/words/_form.html.erb
<%= form_for(word) do |f| %>
<% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> 下記が原因で保存に失敗しました:</h2>

      <ul>
        <% word.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class='form-group'>
<%= f.label :word,'英単語' %>
<%= f.text_field :word, class:'form-control'%>
</div>
<div class='form-group'>
<%= f.label :meaning,'意味' %>
<%= f.text_field :meaning, class:'form-control' %>
</div>
<%= f.submit '単語リストに追加',class:'btn btn-primary' %>

<% end %>

app/views/words/edit.html.erb
<h1>Words#edit</h1>
<p>Find me in app/views/words/edit.html.erb</p>

app/views/words/index.html.erb
  <!--  link_to '削除', word, method: :delete -->
<div class='container-fluid'>
<div class='row'>
<div class='col-md-8 col-md-offset-2 '>
  <div class="page-header">
	<h2><%= current_user.name %>の単語帳</h2>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <td>id</td>
      <td>単語・熟語</td>
      <td>意味</td>
      <td>削除する</td>
    </tr>
  </thead>
  <tbody>
<% @words.each do |word| %>
 
    <tr>
      <td><%= word.id %></td>
      <td><%= word.word %></td>
      <td><%= word.meaning %></td>
      <td><%= link_to '削除', word, method: :delete %></td>
    </tr>
  
<% end %>
  </tbody>
</table>
<%= paginate @words %>

<%= render 'form', word: @word %>
</div>
</div>
</div>

app/views/words/quiz.html.erb
<div class='container-fluid'>
<div class='row'>
<div class='col-md-8 col-md-offset-2 '>

<div class="page-header">
	<h2>単語クイズ</h2>
</div>


<h1>「<%= @quiz.meaning %>」の英単語は？</h1>

<%= link_to '答え', answer_path(@quiz),class:'btn btn-default margin-top1' %>
</div>
</div>
</div>

app/views/words/quiz_answer.html.erb
<div class='container-fluid'>
<div class='row'>
<div class='col-md-8 col-md-offset-2 '>
<div class="page-header">
	<h2>答え</h2>
</div>

<h1>「<%= @answer.word %>」</h1>

<%= link_to '次のクイズへ', quiz_path, class:'btn btn-default margin-top1' %>
<%= link_to '単語一覧に戻る', words_path, class:'btn btn-default margin-top1' %>


</div>
</div>
</div>